<a href="https://colab.research.google.com/github/tzikriamrullah/Data-Mining/blob/main/Crisp_dm_dgn_K_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [127]:
#Import package
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [128]:
#Membaca Data
dataset = pd.read_csv('luaspanen2018.csv')
x = dataset.iloc[:,[2,3]].values
y = dataset.iloc[:, -1].values

In [129]:
#Membaca 5 data teratas
dataset.head()

jenis_tanaman  luas_panen satuan_luas  produksi satuan_produksi
0   Bawang Daun           0          Ha         0         kuintal
1  Bawang Merah           0          Ha         0         kuintal
2  Bawang Putih           0          Ha         0         kuintal
3         Bayam         556          Ha     21337         kuintal
4        Blewah           0          Ha         0         kuintal

In [130]:
#Melihat tipe data yang akan digunakan
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   jenis_tanaman    26 non-null     object
 1   luas_panen       26 non-null     int64 
 2   satuan_luas      26 non-null     object
 3   produksi         26 non-null     int64 
 4   satuan_produksi  26 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.1+ KB


In [131]:
#Menentukan variabel independent
x = dataset.drop(["jenis_tanaman","satuan_luas","satuan_produksi"], axis = 1)
x.head()

luas_panen  produksi
0           0         0
1           0         0
2           0         0
3         556     21337
4           0         0

In [132]:
#Menentukan variable independent
y = dataset["produksi"]
y.head()

0        0
1        0
2        0
3    21337
4        0
Name: produksi, dtype: int64

In [133]:
#Import package model selection dari Sklearn
from sklearn.model_selection import train_test_split
#Membagi data training dan data testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0 )

In [134]:
print(x_train)

    luas_panen  produksi
13           0         0
18           0         0
19           0         0
16           0         0
1            0         0
10           0         0
25           0         0
24           0         0
8            0         0
6            0         0
4            0         0
9            0         0
7            2         4
23           0         0
3          556     21337
0            0         0
21           0         0
15           0         0
12           0         0


In [135]:
print(x_test)

    luas_panen  produksi
2            0         0
20         435     15266
14           1         1
17           0         0
5            0         0
11         681     22961
22           0         0


In [136]:
print(y_train)

13        0
18        0
19        0
16        0
1         0
10        0
25        0
24        0
8         0
6         0
4         0
9         0
7         4
23        0
3     21337
0         0
21        0
15        0
12        0
Name: produksi, dtype: int64


In [137]:
print(y_test)

2         0
20    15266
14        1
17        0
5         0
11    22961
22        0
Name: produksi, dtype: int64


In [138]:
#Mengaftikan package dan syntax untuk mengubah skala data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [139]:
print(x_train)

[[-0.23659587 -0.2357489 ]
 [-0.23659587 -0.2357489 ]
 [-0.23659587 -0.2357489 ]
 [-0.23659587 -0.2357489 ]
 [-0.23659587 -0.2357489 ]
 [-0.23659587 -0.2357489 ]
 [-0.23659587 -0.2357489 ]
 [-0.23659587 -0.2357489 ]
 [-0.23659587 -0.2357489 ]
 [-0.23659587 -0.2357489 ]
 [-0.23659587 -0.2357489 ]
 [-0.23659587 -0.2357489 ]
 [-0.2204836  -0.23490934]
 [-0.23659587 -0.2357489 ]
 [ 4.24261331  4.24264061]
 [-0.23659587 -0.2357489 ]
 [-0.23659587 -0.2357489 ]
 [-0.23659587 -0.2357489 ]
 [-0.23659587 -0.2357489 ]]


In [140]:
print(x_test)

[[-0.23659587 -0.2357489 ]
 [ 3.26782139  2.96840793]
 [-0.22853973 -0.23553901]
 [-0.23659587 -0.2357489 ]
 [-0.23659587 -0.2357489 ]
 [ 5.24962976  4.58349943]
 [-0.23659587 -0.2357489 ]]


In [141]:
#Mengaftikan package untuk klasifikasi KNN dgn imptor clssifie dari SKlearn
from sklearn.neighbors import KNeighborsClassifier
#Mengaftikan fungsi klasifikasi KNN 
classifier = KNeighborsClassifier(n_neighbors = 5)
#Memasukan data training pada fungsi klasifikasi KNN
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [142]:
#Mentukan prediksi
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0])

In [143]:
#Menentukan probabilitas prediksi
classifier.predict_proba(x_test)

array([[1. , 0. , 0. ],
       [0.6, 0.2, 0.2],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0.6, 0.2, 0.2],
       [1. , 0. , 0. ]])

In [144]:
#Import package untuk melihat keakuratan data prediksi dengan data aktual
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[4 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]]


In [145]:
#Ketepatan hasil prediksi
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.57      1.00      0.73         4
           1       0.00      0.00      0.00         1
       15266       0.00      0.00      0.00         1
       22961       0.00      0.00      0.00         1

    accuracy                           0.57         7
   macro avg       0.14      0.25      0.18         7
weighted avg       0.33      0.57      0.42         7



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
