<a href="https://colab.research.google.com/github/tzikriamrullah/Data-Mining/blob/main/DecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import  datasets
import matplotlib.pyplot as plt

In [66]:
iris = datasets.load_iris()
features = iris['data']
target = iris['target']
print(features)
len(features)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

150

In [67]:
decisiontree = DecisionTreeClassifier(random_state=0,
                                      max_depth=None, min_samples_split=2,
                                      min_samples_leaf=1, min_weight_fraction_leaf=0,
                                      max_leaf_nodes=None, min_impurity_decrease=0)

In [68]:
model = decisiontree.fit(features, target)

In [69]:
observation = [[5, 4, 3, 2]]
model.predict(observation)
model.predict_proba(observation)

array([[0., 1., 0.]])

In [70]:
import pydotplus
from sklearn import tree
dot_data = tree.export_graphviz(decisiontree, out_file=None,
                                feature_names=iris['feature_names'],
                                class_names=iris['target_names'])
from IPython.display import Image
graph = pydotplus.graph_from_dot_data(dot_data)
Image(graph.create_png())
graph.write_png("D:\iris.png")

True

In [71]:
#Import numpy, pandas dan sklearn
import numpy as np
import pandas as pd
from sklearn import tree

In [72]:
#membaca dataset dari file ke pandas dataFrame
irisDataset = pd.read_csv('irisDataset.csv', delimiter=';', header=0)

In [73]:
irisDataset.head()

Id  SepalLengthCm  ...  PetalWidthCm          Species
0   1           7.00  ...          1.04  Iris-versicolor
1   2           6.04  ...          1.05  Iris-versicolor
2   3           6.09  ...          1.05  Iris-versicolor
3   4           5.05  ...          1.03  Iris-versicolor
4   5           6.05  ...          1.05  Iris-versicolor

[5 rows x 6 columns]

In [74]:
#Mengubah kelas (Kolom "Species") dari String ke Unique-Integer
irisDataset["Species"] = pd.factorize(irisDataset.Species)[0]

In [75]:
irisDataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1           7.00          3.02           4.07          1.04        0
1   2           6.04          3.02           4.05          1.05        0
2   3           6.09          3.01           4.09          1.05        0
3   4           5.05          2.03           4.00          1.03        0
4   5           6.05          2.08           4.06          1.05        0

In [76]:
print(irisDataset)

     Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0     1           7.00          3.02           4.07          1.04        0
1     2           6.04          3.02           4.05          1.05        0
2     3           6.09          3.01           4.09          1.05        0
3     4           5.05          2.03           4.00          1.03        0
4     5           6.05          2.08           4.06          1.05        0
..  ...            ...           ...            ...           ...      ...
95   96           6.07          3.00           5.02          2.03        1
96   97           6.03          2.05           5.00          1.09        1
97   98           6.05          3.00           5.02          2.00        1
98   99           6.02          3.04           5.04          2.03        1
99  100           5.09          3.00           5.01          1.08        1

[100 rows x 6 columns]


In [77]:
#Menghapus kolom ID
irisDataset = irisDataset.drop(labels="Id", axis=1)

In [78]:
print(irisDataset)

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            7.00          3.02           4.07          1.04        0
1            6.04          3.02           4.05          1.05        0
2            6.09          3.01           4.09          1.05        0
3            5.05          2.03           4.00          1.03        0
4            6.05          2.08           4.06          1.05        0
..            ...           ...            ...           ...      ...
95           6.07          3.00           5.02          2.03        1
96           6.03          2.05           5.00          1.09        1
97           6.05          3.00           5.02          2.00        1
98           6.02          3.04           5.04          2.03        1
99           5.09          3.00           5.01          1.08        1

[100 rows x 5 columns]


In [79]:
#Mengubah Data Frame ke array Numpy
irisDataset = irisDataset.to_numpy()

In [80]:
#Membagi Dataset => 80 baris data untuk training dan 20 data untuk testing
dataTraining = np.concatenate((irisDataset[0:40, :], irisDataset[50:90, :]),
                              axis=0)
dataTesting = np.concatenate((irisDataset[0:40, :], irisDataset[50:90, :]),
                              axis=0)

In [81]:
print(dataTesting)
len(dataTesting)

[[7.   3.02 4.07 1.04 0.  ]
 [6.04 3.02 4.05 1.05 0.  ]
 [6.09 3.01 4.09 1.05 0.  ]
 [5.05 2.03 4.   1.03 0.  ]
 [6.05 2.08 4.06 1.05 0.  ]
 [5.07 2.08 4.05 1.03 0.  ]
 [6.03 3.03 4.07 1.06 0.  ]
 [4.09 2.04 3.03 1.   0.  ]
 [6.06 2.09 4.06 1.03 0.  ]
 [5.02 2.07 3.09 1.04 0.  ]
 [5.   2.   3.05 1.   0.  ]
 [5.09 3.   4.02 1.05 0.  ]
 [6.   2.02 4.   1.   0.  ]
 [6.01 2.09 4.07 1.04 0.  ]
 [5.06 2.09 3.06 1.03 0.  ]
 [6.07 3.01 4.04 1.04 0.  ]
 [5.06 3.   4.05 1.05 0.  ]
 [5.08 2.07 4.01 1.   0.  ]
 [6.02 2.02 4.05 1.05 0.  ]
 [5.06 2.05 3.09 1.01 0.  ]
 [5.09 3.02 4.08 1.08 0.  ]
 [6.01 2.08 4.   1.03 0.  ]
 [6.03 2.05 4.09 1.05 0.  ]
 [6.01 2.08 4.07 1.02 0.  ]
 [6.04 2.09 4.03 1.03 0.  ]
 [6.06 3.   4.04 1.04 0.  ]
 [6.08 2.08 4.08 1.04 0.  ]
 [6.07 3.   5.   1.07 0.  ]
 [6.   2.09 4.05 1.05 0.  ]
 [5.07 2.06 3.05 1.   0.  ]
 [5.05 2.04 3.08 1.01 0.  ]
 [5.05 2.04 3.07 1.   0.  ]
 [5.08 2.07 3.09 1.02 0.  ]
 [6.   2.07 5.01 1.06 0.  ]
 [5.04 3.   4.05 1.05 0.  ]
 [6.   3.04 4.05 1.0

80

In [82]:
#Memecah dataset ke Inpt dan Label
inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
labelTraining = dataTraining[:, 4]
labelTesting = dataTesting[:, 4]
print(labelTraining)
len(labelTraining)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1.]


80

In [83]:
#Mendefinisikan DecisinTree Classifier
model = tree.DecisionTreeClassifier()

In [84]:
#Mentraining Model
model = model.fit(inputTraining, labelTraining)

In [87]:
#Memprediksi Input Data Testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya", labelTesting)
print("Hasil Prediksi :", hasilPrediksi)

Label Sebenarnya [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1.]
Hasil Prediksi : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1.]


In [89]:
#Menghitung Akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Predisi Benar :", prediksiBenar, "data")
print("Predisi Salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Predisi Benar : 80 data
Predisi Salah : 0 data
Akurasi : 100.0 %
