<a href="https://colab.research.google.com/github/tzikriamrullah/Data-Mining/blob/main/K_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Covid19.csv')
x = dataset.iloc[:, [1,8]].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[[     2015 104000000]
 [     2015  96000000]
 [     2015  61000000]
 ...
 [     2021   1000000]
 [     2021   1000000]
 [     2021   1000000]]


In [ ]:
print(y)

[104000000 200000000 262000000 ...  45000000  46000000  47000000]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0 )

In [ ]:
print(x_train)

[[    2019  1000000]
 [    2016     1000]
 [    2020 13000000]
 ...
 [    2017        0]
 [    2017 35000000]
 [    2019 24000000]]


In [ ]:
print(x_test)

[[     2019      1000]
 [     2015 110000000]
 [     2016         0]
 ...
 [     2019  11000000]
 [     2020   5000000]
 [     2017   1000000]]


In [ ]:
print(y_train)

[2027000000     718000 5544000000 ...      31000 9471000000 8818000000]


In [ ]:
print(y_test)

[     146000 32663000000    63000000 ...  1636000000  4067000000
   116000000]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
print(x_train)

[[ 0.7602004  -0.53377838]
 [-0.9039764  -0.55326009]
 [ 1.314926   -0.29976383]
 ...
 [-0.3492508  -0.5532796 ]
 [-0.3492508   0.12926286]
 [ 0.7602004  -0.08525048]]


In [ ]:
print(x_test)

[[ 0.7602004  -0.55326009]
 [-1.458702    1.59185385]
 [-0.9039764  -0.5532796 ]
 ...
 [ 0.7602004  -0.33876625]
 [ 1.314926   -0.45577353]
 [-0.3492508  -0.53377838]]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
print(x_test)

[[ 0.7602004  -0.55326009]
 [-1.458702    1.59185385]
 [-0.9039764  -0.5532796 ]
 ...
 [ 0.7602004  -0.33876625]
 [ 1.314926   -0.45577353]
 [-0.3492508  -0.53377838]]


In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[3 0 0 ... 0 0 0]
 [3 0 0 ... 0 0 0]
 [2 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
from matplotlib.colors import ListedColormap
x_set, y_set = x_train, y_train
x1, x2 = np.meshgrid(np.arange(start = x_set[:, 0].min() -1, stop = x_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = x_set[:, 1].min() -1, stop = x_set[:, 1].max() + 1, step = 0.01))
plt.contourf(x1, x2, classifier.predict(np.array([x1.ravel(), x2.ravel()]).T).reshape(x1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(x1.min(), x1.max())
plt.ylim(x2.min(), x2.max())
for i, j in enumerate(np.unique(y_set)):
  plt.scatter(x_set[y_set == j, 0], x_set[y_set == j, 1],
              c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('K-NN(Training set')
plt.xlabel('age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

In [ ]:
from matplotlib.colors import ListedColormap
x_set, y_set = x_train, y_train
x1, x2 = np.meshgrid(np.arange(start = x_set[:, 0].min() -1, stop = x_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = x_set[:, 1].min() -1, stop = x_set[:, 1].max() + 1, step = 0.01))
plt.contourf(x1, x2, classifier.predict(np.array([x1.ravel(), x2.ravel()]).T).reshape(x1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(x1.min(), x1.max())
plt.ylim(x2.min(), x2.max())
for i, j in enumerate(np.unique(y_set)):
  plt.scatter(x_set[y_set == j, 0], x_set[y_set == j, 1],
              c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('K-NN(Testing set')
plt.xlabel('year')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()