In [24]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


Numpy merupakan library python digunkan untuk komputasi matrik.

Matplotlib merupakan library python untukk presentaasi data berupa grafik atau plot.

Pandas merupakan Library Python.

In [25]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Memanggil Data.csv kemudian disimpan kedalam variabel x dan y

In [26]:
print(x)

[['Buku' 12.0 32000.0]
 ['pensil' 33.0 44000.0]
 ['Buku' 53.0 12000.0]
 ['pensil' 20.0 33000.0]
 ['pulpen' 34.0 nan]
 ['pensil' 61.0 76000.0]
 ['buku' nan 34000.0]
 ['pulpen' 21.0 30000.0]
 ['buku' 22.0 16000.0]
 ['pensil' 41.0 54000.0]]


In [27]:
print(y)

['Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No']


In [28]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

Memberikan nilai missing value dengan nilai rata-rata

In [29]:
print(x)

[['Buku' 12.0 32000.0]
 ['pensil' 33.0 44000.0]
 ['Buku' 53.0 12000.0]
 ['pensil' 20.0 33000.0]
 ['pulpen' 34.0 36777.77777777778]
 ['pensil' 61.0 76000.0]
 ['buku' 33.0 34000.0]
 ['pulpen' 21.0 30000.0]
 ['buku' 22.0 16000.0]
 ['pensil' 41.0 54000.0]]


In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

di Encode dengan OneHotEncoder untuk mendapatkan matrik

In [32]:
print(x)

[[0.0 1.0 0.0 0.0 0.0 12.0 32000.0]
 [1.0 0.0 0.0 1.0 0.0 33.0 44000.0]
 [0.0 1.0 0.0 0.0 0.0 53.0 12000.0]
 [1.0 0.0 0.0 1.0 0.0 20.0 33000.0]
 [1.0 0.0 0.0 0.0 1.0 34.0 36777.77777777778]
 [1.0 0.0 0.0 1.0 0.0 61.0 76000.0]
 [1.0 0.0 1.0 0.0 0.0 33.0 34000.0]
 [1.0 0.0 0.0 0.0 1.0 21.0 30000.0]
 [1.0 0.0 1.0 0.0 0.0 22.0 16000.0]
 [1.0 0.0 0.0 1.0 0.0 41.0 54000.0]]


In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

Encoder Label x dan y menggunakan LabelEncoder

In [16]:
print(y)

[1 0 1 1 0 0 1 0 1 0]


In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

Membagi menggunakan train_test_split size 0.2

In [40]:
print(x_train)

[[1.0 0.0 1.0 0.0 0.0 33.0 34000.0]
 [1.0 0.0 0.0 0.0 1.0 34.0 36777.77777777778]
 [0.0 1.0 0.0 0.0 0.0 12.0 32000.0]
 [1.0 0.0 0.0 1.0 0.0 20.0 33000.0]
 [1.0 0.0 0.0 1.0 0.0 33.0 44000.0]
 [1.0 0.0 0.0 0.0 1.0 21.0 30000.0]
 [1.0 0.0 1.0 0.0 0.0 22.0 16000.0]
 [1.0 0.0 0.0 1.0 0.0 61.0 76000.0]]


In [19]:
print(x_test)

[[1.0 0.0 0.0 0.0 53.0 12000.0]
 [0.0 0.0 1.0 0.0 41.0 54000.0]]


In [20]:
print(y_train)

[1 0 1 1 0 0 1 0]


In [38]:
print(y_test)

[1 0]


In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

Scaling mengunakan StandarrdScaler agar tidak terlalu besar angkanya

In [36]:
print(x_train)

[[1.0 0.0 1.0 -0.7745966692414834 -0.5773502691896258 0.2504796934375796
  -0.22941976867703762]
 [1.0 0.0 0.0 -0.7745966692414834 1.7320508075688774 0.3220453201340309
  -0.058210986082233074]
 [0.0 1.0 0.0 -0.7745966692414834 -0.5773502691896258 -1.252398467187898
  -0.35269009214529673]
 [1.0 0.0 0.0 1.2909944487358056 -0.5773502691896258 -0.6798734536162875
  -0.29105493041116715]
 [1.0 0.0 0.0 1.2909944487358056 -0.5773502691896258 0.2504796934375796
  0.386931848664258]
 [1.0 0.0 0.0 -0.7745966692414834 1.7320508075688774 -0.6083078269198362
  -0.47596041561355584]
 [1.0 0.0 1.0 -0.7745966692414834 -0.5773502691896258 -0.5367422002233849
  -1.3388526798913696]
 [1.0 0.0 0.0 1.2909944487358056 -0.5773502691896258 2.2543172409382164
  2.359257024156404]]


In [37]:
print(x_test)

[[0.0 1.0 0.0 -0.7745966692414834 -0.5773502691896258 1.681792227366606
  -1.585393326827888]
 [1.0 0.0 0.0 1.2909944487358056 -0.5773502691896258 0.8230047070091902
  1.0032834660055536]]
